### ISSUE TITLE
At 22%, failed to install a dependency 

### ISSUE THREAD

**Issue by NumericanPi** [host505/repository.host505#16] opened 2022-03-01 03:45 UTC
TheOath was working just fine and then whenever I go to movies it says TheOath required to use this feature you must download an add-on the oath would you like to download this add on so I click yes it says installing then on dependencies, it gets about 1/6 of the way, then it says failed to install a dependency.

When I go to add-ons and attempt to install the oath it fails at 22%. It appears that repository.orion is where it's failing and that is not an optional add-on. Other dependencies with Orion in their names are optional.

**Comment by eeden003** [comment] 2022-03-01 06:44
Are you using Kodi18 or 19 ? Why not trying to install the Repo Orion first and installing Orion itself after that ?! Also, what version of The Oathj are you using ? The version......10 had issus at my PV, the newest version .......11 works great.

**Comment by host505** [comment] 2022-03-01 06:49
The issue is this: https://github.com/host505/repository.host505/issues/15 and should be fixed now.
Force check for updates.

**Closed** 2022-03-01 08:57 UTC
