### ISSUE TITLE
Trakt lists not showing

### ISSUE THREAD

**Issue by DB-42** [host505/repository.host505#3] opened 2021-03-19 15:56 UTC
First I'd like to thank you for the work you've done. The Oath was one of the first to work with Kodi 19. 

When I want to watch a movie or TV show I usually go to my Trakt lists. For my movies I use Trakt Watchlist (a default list).  I've also created 2-3 personal lists.  My TV shows, My watched TV shows, and another for movies I don't want the family to see displayed.

The Trakt watchlist will display the movies, and My TV shows will also display the shows.   When I try to open My watched TV shows or the other movies.....the blue circle spins for a few seconds then stops.  It will never display what's there.  I also have a few "Liked Lists" that do not show either.

**Comment by host505** [comment] 2021-03-19 18:20
Can't reproduce.
Do you perhaps have 'hide watched' enabled in Kodi?

**Comment by DB-42** [comment] 2021-03-19 23:47
Sorry for just getting back to you now...I just got home from work

Thank you for responding.  In Settings>TheOath>Hide movies in cinema   that is not enabled.

I see you updated to 4.00.07 5 hours ago....but when I check your repo it says no updates....still shows 4.00.06.  What is the correct repo address?  I have   https://host505.github.io/

I'm using the Nvidia Shield pro 2019. I only have 3 addons installed...TheOath, Fen, and Shadow.  Also I have Trakt installed.  The problem I'm having with the Oath  I also have the same problem with Fen.  The only one that's working correct is Shadow. Thank you

**Comment by host505** [comment] 2021-03-20 00:01
No, I'm not talking about a setting in theoath, but a kodi setting/option where it hides stuff that are marked as watched.
It's skin dependant where you can find it, it's on any video list on the side menu.
About updates, just force check for updates on kodi's add-on manager.

**Comment by DB-42** [comment] 2021-03-20 00:34
I don't use any custom skins. Just the stock one that comes with Kodi.   Funny my time was wrong on the Shield. After changing the time I was able to update TheOath.

**Comment by host505** [comment] 2021-03-20 14:33
Well stock one is a skin too.
Research how to make kodi show you all items, watched and unwatched.
Since it happens on 2 add-ons, and I can't reproduce the problem on any of my systems, nor have I any other reports of this, I assume it's something at your end.
Can't really say for sure without a log though.

**Comment by DB-42** [comment] 2021-03-20 16:09
I took a picture with my phone when I got the error using Fen.  I don't know why it happens with TheOath and FEN but not with Shadow?

![006](https://user-images.githubusercontent.com/55021031/111876375-cc326b00-8974-11eb-8178-2655af3f88fb.JPG)
![007](https://user-images.githubusercontent.com/55021031/111876379-ce94c500-8974-11eb-8583-3cf6f3a46acd.JPG)

![007](https://user-images.githubusercontent.com/55021031/111876427-13b8f700-8975-11eb-803e-857ff37a796c.JPG)
![006](https://user-images.githubusercontent.com/55021031/111876428-14ea2400-8975-11eb-8054-3953d57090ee.JPG)

**Comment by DB-42** [comment] 2021-03-20 16:10
Sorry for the doubles

**Comment by host505** [comment] 2021-03-20 16:28
Really, cropped log photos of another add-on?? What am I supposed to get out of this?
And you still haven't answered if you have 'hide watched' enabled.
It's of your interest to send me a link to a paste site containing your clean (after restart), full debug log capturing the problem.
Otherwise - no issue - working fine for everyone else.

**Comment by DB-42** [comment] 2021-03-20 16:39
No I do not have "hide watched" enabled anywhere.  These are movies I haven't watched.

**Comment by DB-42** [comment] 2021-03-20 16:46
Alright I'm going to try uninstalling Oath then re-installing it.  What should I delete to totally clean out everything with TheOath?

**Comment by DB-42** [comment] 2021-03-21 01:10
I uninstalled everything for TheOath including the repo.  Then I downloaded the repo>tried to install Oath and it says Failed to install addon from zip>the dependency on script.theoath.artworkversion 0.0.0 could not be satisfied.

**Comment by host505** [comment] 2021-03-28 17:33
On recent versions you can upload your add-on logging through the add-on's Tools menu.
1. go to add-on's settings and enable debugging
2. reproduce the issue
3. go to Tools/Log Functions/Upload log
4. post here the link you'll be given from the add-on
5. re-disable logging on add-on's settings

**Comment by DB-42** [comment] 2021-03-28 19:56
> 
> 
> On recent versions you can upload your add-on logging through the add-on's Tools menu.
> 
>     1. go to add-on's settings and enable debugging
> 
>     2. reproduce the issue
> 
>     3. go to Tools/Log Functions/Upload log
> 
>     4. post here the link you'll be given from the add-on
> 
>     5. re-disable logging on add-on's settings

Would I need to enable debugging within Kodi as well as enable debugging in The Oath?

**Comment by host505** [comment] 2021-03-28 20:32
Nope

**Comment by DB-42** [comment] 2021-03-28 20:38
I'll do that now

**Comment by DB-42** [comment] 2021-03-28 20:56
https://paste.kodi.tv/orajeyotuw

**Comment by host505** [comment] 2021-03-28 21:06
Yea just says list is empty.
Would you mind send me a link to your list, so I can 'like' it so it will appear on my lists and see what's going on.
You can email it to me if you don't want it public (I think you can see my mail on my profile here)

**Comment by DB-42** [comment] 2021-03-28 21:38
Ok I sent you the link

**Comment by DB-42** [comment] 2021-03-29 12:10
Your suggestion to change the list from Release Date to Title worked.  Now I can see my list in The Oath. 
I want to thank you for helping me with this issue. I really do appreciate you taking your time to resolve this problem, and for all the great work you've done to make The Oath a top addon.  Thanks again.

**Comment by host505** [comment] 2021-03-29 14:12
The problem was that if the list is sorted on trakt by release date, and an item in it has no release date on trakt api, the whole list fails to load.
It will be fixed on next update - for now sort your lists differently.
Items with no release date are excluded from listing though - i'll look if there's good reason for it.

**Comment by DB-42** [comment] 2021-03-29 14:45
> 
> 
> The problem was that if the list is sorted on trakt by release date, and an item in it has no release date on trakt api, the whole list fails to load.
> It will be fixed on next update - for now sort your lists differently.
> Items with no release date are excluded from listing though - i'll look if there's good reason for it.

I have sorted my list differently and now it's working.  Thanks.
You can close this issue if you like.

**Comment by host505** [comment] 2021-03-29 21:24
fixed in 4.00.13

**Closed by host505** 2021-03-29 21:24 UTC
