### ISSUE TITLE
Trakt Progress

### ISSUE THREAD

**Issue by derrgoo** [host505/repository.host505#4] opened 2021-03-28 13:29 UTC
I really like oath. One issue I have not been able to figure out is how to get fanart on my trakt tv progress to show up? It just pulls regular pictures. Can we have a regular fanart?

**Comment by host505** [comment] 2021-03-28 17:10
Duplicate of https://github.com/host505/plugin.video.theoath/issues/20

**Closed by host505** 2021-03-28 17:10 UTC
